### ISSUE TITLE
Receving Exception: "Stream is terminated. SourceQueue is detached"

### ISSUE THREAD

**Issue by has981** [gilt/gfc-aws-kinesis#29] opened 2017-07-09 10:05 UTC
I'm using "com.gilt" %% "gfc-aws-kinesis-akka" % "0.12.1" in my akka (v2.4.17), scala (v2.12.1) project to consume from a kinesis stream.

Following instructions in akka.md, I'm using the 1st code snippet (For already materialized stream)

After running (in staging) for a long time (1 day) I start receiving exceptions for any new record being pushed to the stream with the cause "Stream is terminated. SourceQueue is detached"

I've added a SO question [there](https://stackoverflow.com/questions/44983989/akka-streams-with-gilt-aws-kinesis-exception-stream-is-terminated-sourcequeue) with all the details, but for convenience here is the code:

    ...
    val streamConfig = KinesisStreamConsumerConfig[String](
      streamName = queueName
      , applicationName = kinesisConsumerApp
      , regionName = Some(awsRegion)
      , checkPointInterval = 5.minutes
      , retryConfig = RetryConfig(initialDelay = 1.second, retryDelay = 1.second, maxRetries = 3)
      , initialPositionInStream = InitialPositionInStream.LATEST
    )

    implicit val mat = ActorMaterializer()

    val flow = Source.queue[String](0, OverflowStrategy.backpressure)
      .to(Sink.foreach {
        msgBody => {
          log.info(s"Flow got message: $msgBody")
          try {
            val workAsJson = parse(msgBody)
            frontEnd ! workAsJson
          } catch {
            case th: Throwable => log.error(s"Exception thrown trying to parse message from Kinesis stream, e.cause: ${th.getCause}, e.message: ${th.getMessage}")
          }
        }
      })
      .run()

    val consumer = new KinesisStreamConsumer[String](
      streamConfig,
      KinesisStreamHandler(
        KinesisStreamSource.pumpKinesisStreamTo(flow, 10.second)
      )
    )

    val ec = Executors.newSingleThreadExecutor()
    ec.submit(new Runnable {
      override def run(): Unit = consumer.run()
    })

... and here is the stack dump:

```
INFO: Sleeping ...                                                                                                                                                                     [863/1962]
 DEBUG[RecordProcessor-0000] KCLRecordProcessorFactory$IRecordProcessorFactoryImpl - Processing 1 records from shard shardId-000000000000
 WARN [RecordProcessor-0000] KCLRecordProcessorFactory$IRecordProcessorFactoryImpl - Kinesis shard: shardId-000000000000 :: Stream is terminated. SourceQueue is detached
 WARN [RecordProcessor-0000] KCLRecordProcessorFactory$IRecordProcessorFactoryImpl - Kinesis shard: shardId-000000000000 :: Stream is terminated. SourceQueue is detached
 WARN [RecordProcessor-0000] KCLRecordProcessorFactory$IRecordProcessorFactoryImpl - Kinesis shard: shardId-000000000000 :: Stream is terminated. SourceQueue is detached
 ERROR[RecordProcessor-0000] KCLRecordProcessorFactory$IRecordProcessorFactoryImpl - SKIPPING 1 records from shard shardId-000000000000 :: Kinesis shard: shardId-000000000000 :: Stream is termi
nated. SourceQueue is detached
com.gilt.gfc.aws.kinesis.client.KCLRecordProcessorFactory$KCLProcessorException: Kinesis shard: shardId-000000000000 :: Stream is terminated. SourceQueue is detached
        at com.gilt.gfc.aws.kinesis.client.KCLRecordProcessorFactory$IRecordProcessorFactoryImpl$$anon$1.$anonfun$doRetry$2(KCLRecordProcessorFactory.scala:156)
        at com.gilt.gfc.util.Retry$.retryWithExponentialDelay(Retry.scala:67)
        at com.gilt.gfc.aws.kinesis.client.KCLRecordProcessorFactory$IRecordProcessorFactoryImpl$$anon$1.doRetry(KCLRecordProcessorFactory.scala:151)
        at com.gilt.gfc.aws.kinesis.client.KCLRecordProcessorFactory$IRecordProcessorFactoryImpl$$anon$1.processRecords(KCLRecordProcessorFactory.scala:120)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:176)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Stream is terminated. SourceQueue is detached
        at akka.stream.impl.QueueSource$$anon$1.$anonfun$postStop$1(Sources.scala:57)
        at akka.stream.impl.QueueSource$$anon$1.$anonfun$postStop$1$adapted(Sources.scala:56)
        at akka.stream.stage.CallbackWrapper.$anonfun$invoke$1(GraphStage.scala:1373)
        at akka.stream.stage.CallbackWrapper.locked(GraphStage.scala:1379)
        at akka.stream.stage.CallbackWrapper.invoke(GraphStage.scala:1370)
        at akka.stream.stage.CallbackWrapper.invoke$(GraphStage.scala:1369)
        at akka.stream.impl.QueueSource$$anon$1.invoke(Sources.scala:47)
        at akka.stream.impl.QueueSource$$anon$2.offer(Sources.scala:180)
        at com.gilt.gfc.aws.kinesis.akka.KinesisStreamSource$.$anonfun$pumpKinesisStreamTo$1(KinesisStreamSource.scala:20)
        at com.gilt.gfc.aws.kinesis.akka.KinesisStreamSource$.$anonfun$pumpKinesisStreamTo$1$adapted(KinesisStreamSource.scala:20)
        at com.gilt.gfc.aws.kinesis.akka.KinesisStreamHandler$$anon$1.onRecord(KinesisStreamHandler.scala:29)
        at com.gilt.gfc.aws.kinesis.akka.KinesisStreamConsumer.$anonfun$run$1(KinesisStreamConsumer.scala:40)
        at com.gilt.gfc.aws.kinesis.akka.KinesisStreamConsumer.$anonfun$run$1$adapted(KinesisStreamConsumer.scala:40)
        at com.gilt.gfc.aws.kinesis.client.KCLWorkerRunner.$anonfun$runSingleRecordProcessor$2(KCLWorkerRunner.scala:159)
        at com.gilt.gfc.aws.kinesis.client.KCLWorkerRunner.$anonfun$runSingleRecordProcessor$2$adapted(KCLWorkerRunner.scala:159)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at com.gilt.gfc.aws.kinesis.client.KCLWorkerRunner.$anonfun$runSingleRecordProcessor$1(KCLWorkerRunner.scala:159)
        at com.gilt.gfc.aws.kinesis.client.KCLWorkerRunner.$anonfun$runSingleRecordProcessor$1$adapted(KCLWorkerRunner.scala:159)
        at com.gilt.gfc.aws.kinesis.client.KCLWorkerRunner.$anonfun$runBatchProcessor$1(KCLWorkerRunner.scala:121)
        at com.gilt.gfc.aws.kinesis.client.KCLWorkerRunner.$anonfun$runBatchProcessor$1$adapted(KCLWorkerRunner.scala:116)
        at com.gilt.gfc.aws.kinesis.client.KCLRecordProcessorFactory$IRecordProcessorFactoryImpl$$anon$1.$anonfun$processRecords$2(KCLRecordProcessorFactory.scala:120)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at com.gilt.gfc.aws.kinesis.client.KCLRecordProcessorFactory$IRecordProcessorFactoryImpl$$anon$1.$anonfun$doRetry$2(KCLRecordProcessorFactory.scala:153)
        ... 11 common frames omitted
```

**Update**:

In case it may help, by increasing the stream's `Source.queue` size to 100, I've been able to make the application run for 3+ days without encountering subject issue. (had to restart for a different reason)

**Comment by mikegirkin** [comment] 2017-07-11 09:27
Hi @has981 !

We've never encounter this problem before, and it is very unclear what is causing it, so couldn't give you an answer. We'll try to reproduce the problem and find out what's happening.

**Comment by mikegirkin** [comment] 2017-08-08 12:52
So, what I find out is - application fails because `queue.offer` fails. Not sure yet, why this happens, still investigating.

**Comment by mikegirkin** [comment] 2017-08-15 13:49
So, I managed to reproduce that thing. In my case that happened when the stream that this source was pumping too died because of exception. @has981, @tunesmith could you please put the follwing lines where you create your ActorMaterializer:
```

**Comment by has981** [comment] 2017-08-17 13:41
thanks @mikegirkin for your input on this, I've added the lines you mentioned in my code. Will post here again once the issue re-appears.

**Comment by tunesmith** [comment] 2018-01-13 05:14
The above tip worked for me and the added exception handling closed this issue for us, thanks!

**Comment by mikegirkin** [comment] 2018-01-23 10:16
Seems to be resolved

**Closed by mikegirkin** 2018-01-23 10:16 UTC
